version: 2.1
workflows:
  amplify-ios-getting-started:
    jobs:
      - pre-build
      - build:
          requires:
              - pre-build
      - test:
          requires:
              - build
      - deploy:
          requires:
              - test
      - post-build:
          requires:
              - deploy

jobs:
  pre-build:
    machine: true
    resource_class: sebsto/amplify-ios-getting-started
    steps:
      - checkout
      - run: pwd && ls -al
      - run: code/ci_actions/01_keychain.sh
      - run: code/ci_actions/02_amplify.sh

  build:
    machine: true
    resource_class: sebsto/amplify-ios-getting-started
    steps:
      - checkout
      - run: pwd && ls -al
      - run: code/ci_actions/03_build.sh

  test:
    machine: true
    resource_class: sebsto/amplify-ios-getting-started
    steps:
      - checkout
      - run: echo "Test"

  deploy:
    machine: true
    resource_class: sebsto/amplify-ios-getting-started
    steps:
      - checkout
      - run: echo "deploy"

  post-build:
    machine: true
    resource_class: sebsto/amplify-ios-getting-started
    steps:
      - checkout
      - run: echo "Post build"
