name: ContinuousIntegration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: PrepareKeychain
      run: code/ci_actions/01_keychain.sh
    - name: PrepareAmplify
      run: code/ci_actions/02_amplify.sh
    - name: Build
      run: code/ci_actions/03_build.sh

  test:

    needs: build
    
    runs-on: self-hosted

    steps:

    - name: UnitTest
      run: code/ci_actions/04_unit_tests.sh
    - name: UITest
      run: code/ci_actions/05_ui_tests.sh

  cleanup:

    needs: test
    
    runs-on: self-hosted

    steps:

    - name: cleanup
      run: code/ci_actions/06_cleanup.sh
